package hackbreakers.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import hackbreakers.dbms.Attribute;
import hackbreakers.dbms.DataType;
import hackbreakers.dbms.Database;
import hackbreakers.dbms.Entity;

public class CreateEntityJDialog extends javax.swing.JDialog {//Contains: 7 methods, 251 lines.

    /**
     * Creates new form CreateEntityJDialog
     */
    public CreateEntityJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JTextField getDatabaseNameJTextField() {
        return databaseNameJTextField;
    }

    public void setDatabaseNameJTextField(JTextField databaseNameJTextField) {
        this.databaseNameJTextField = databaseNameJTextField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entityNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attributesJTable = new javax.swing.JTable();
        okJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        dbNameJLabel = new javax.swing.JLabel();
        databaseNameJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Table");

        jLabel1.setText("Entity Name");

        jLabel2.setText("Attributes");

        attributesJTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Name", "Datatype"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        attributesJTable.setColumnSelectionAllowed(true);
        attributesJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        attributesJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(attributesJTable);
        attributesJTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        okJButton.setText("OK");
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        addJButton.setText("+");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setText("-");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        dbNameJLabel.setText("Database");

        databaseNameJTextField.setEditable(false);
        databaseNameJTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(okJButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cancelJButton))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(addJButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteJButton))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(dbNameJLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(entityNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                                        .addComponent(databaseNameJTextField))))
                                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dbNameJLabel)
                                        .addComponent(databaseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(entityNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(addJButton)
                                        .addComponent(deleteJButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(okJButton)
                                        .addComponent(cancelJButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {

        this.dispose();
    }

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //Shows the entity's name.
        String entityName = this.entityNameJTextField.getText();
        //Reads the entity's attributes through the jTable.
        List<Attribute> attrList = new ArrayList();
        for (int i = 0; i < this.attributesJTable.getModel().getRowCount(); i++) {
            attrList.add(
                    new Attribute((String) this.attributesJTable.getModel().getValueAt(i, 0),
                            new DataType((String) this.attributesJTable.getModel().getValueAt(i, 1)))
            );
        }

        //Stores the new entity in the (.sys) file and adds it to db's jTree.
        Database db = new Database();
        if (db.createEntityGUI(this.databaseNameJTextField.getText(), entityName, attrList)) {
            //A message of successful storage is appeared.
            JOptionPane.showMessageDialog(this, "Succesfully created entity with name " + entityName + " !");
            //Updates the jTree.
            MainFrame mainFrm = (MainFrame) this.getParent();
            JScrollPane jScrollPane = mainFrm.getDbObjectsTreeJScrollPane();
            JTree entityTree = (JTree) jScrollPane.getViewport().getView();
            DefaultTreeModel model = (DefaultTreeModel) entityTree.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) entityTree.getModel().getRoot();
            DefaultMutableTreeNode child = new DefaultMutableTreeNode(entityName);
            model.insertNodeInto(child, root, root.getChildCount());
            entityTree.scrollPathToVisible(new TreePath(child.getPath()));
        } else {
            //Otherwise, an error message is appeared.
            JOptionPane.showMessageDialog(this, "Could not create entity with name " + entityName + "...",
                    "Entity exists or other error",
                    JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //Pulls the entities from the database.
        Database db = new Database();
        List<Entity> entList = db.fetchDatabaseEntitiesGUI(this.databaseNameJTextField.getText());
        //Adds new row on the jTable.
        TableColumn dataTypeColumn = this.attributesJTable.getColumnModel().getColumn(1);
        DefaultTableModel tableModel = (DefaultTableModel) this.attributesJTable.getModel();
        JComboBox comboBox = new JComboBox();
        comboBox.addItem("Numeric");
        comboBox.addItem("Characters");
        comboBox.addItem("Boolean");
        comboBox.addItem("Date");
        dataTypeColumn.setCellEditor(new DefaultCellEditor(comboBox));
        tableModel.addRow(new Object[]{"", ""});
    }

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {

        DefaultTableModel model = (DefaultTableModel) this.attributesJTable.getModel();
        model.removeRow(this.attributesJTable.getSelectedRow());
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addJButton;
    private javax.swing.JTable attributesJTable;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JTextField databaseNameJTextField;
    private javax.swing.JLabel dbNameJLabel;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JTextField entityNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okJButton;
    // End of variables declaration
}
